services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - btg_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  posts_backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - btg_network
    restart: unless-stopped

  posts_frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      posts_backend:
        condition: service_healthy
    networks:
      - btg_network
    restart: unless-stopped

volumes:
  mssql_data:

networks:
  btg_network:
    driver: bridge
