"""create posts table

Revision ID: 7e986f367327
Revises: 
Create Date: 2026-07-31 04:00:25.923249

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '7e986f367327'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "nombre",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "descripcion",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "resumen",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
